
const Footer = () => {
    return (
        <footer className="text-gray-700 text-center">
            <p>Generated by Lucas Maggio - Palma de Mallorca  +34 692185000</p>
        </footer>
    );
};

export default Footer;