"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalStateProvider } from "@/app/context/GlobalState";
import Modal from "react-modal";
import { useEffect } from "react";
// import { Metadata } from "next";
import { ApolloWrapper } from './../lib/apollo-provider.js'

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "1009 Tattoo budget generator system",
//   description: "Generated by Lucas Maggio, +34 692185000",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    if (typeof window !== "undefined") {
      Modal.setAppElement("#__next");
    }
  }, []);
  return (
    <>
      <GlobalStateProvider>
        <html lang="en">
          <body className={inter.className}>
            <ApolloWrapper>
              <div id="__next">
                {children}
              </div>
            </ApolloWrapper>
          </body>
        </html>
      </GlobalStateProvider>
    </>
  );
}
