import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalStateProvider } from "@/app/context/GlobalState";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GlobalStateProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* <header>###_Layout general_### Sistema de agenda de tattoo </header> */}
          {children}
          {/* <footer className="py-10 flex justify-center items-center">
          ###_Footer_### 1009 Tattoo - Ushuaia, Tierra del fuego. 2024
        </footer> */}
        </body>
      </html>
    </GlobalStateProvider>
  );
}
